# Usa uma imagem Node para rodar o Angular CLI
FROM node:lts-alpine AS angular-dev

# Define o diretório de trabalho
WORKDIR /app

# Copia package.json e instala dependências
# Otimiza o cache, pois dependências raramente mudam
COPY package.json package-lock.json ./
RUN npm install

# Copia o restante da aplicação
COPY . .

# Porta padrão do servidor de desenvolvimento Angular
EXPOSE 4200

CMD ["npm", "run", "start"]
